export const START_PHRASES = [
  "Let's go!",
  "Let's do this!",
  'Commence-erado!',
  'Fire away!',
  'Clock me in!',
  'Off we pop!',
  'Engage!',
  'Hit it!',
  'Game on!',
  "And we're off!",
  'Begin-a-rooni!',
  'Away we go!',
  'Crack on!',
  'Do the thing!',
  'Make it happen!',
  'Time to shine!',
  'Punch it!',
  'Go, go, go!',
  'Start the clock!',
  'Roll camera!',
  'Cue the magic!',
  'Launch mode!',
  'Activate!',
  'Here we go!',
  'Get cracking!',
  'Onward!',
  'Let it rip!',
  'Into the fray!',
  'Tally-ho!',
  'Worky worky!',
  'Beginify!',
  'Full steam!',
  'Show time!',
  'Lights on!',
  'Blast off!',
  'Hop to it!',
  'Tickety-boo!',
  'Start me up!',
  'Go bananas!',
  'Make time!',
  "Clock o'clock!",
  'Deploy!',
  'Get busy!',
  'Start-a-mundo!',
  'Time flies!',
  'Zoom zoom!',
  "Let's cook!",
  'Eyes on!',
  'Blink and go!',
]

export function randomStartPhrase(): string {
  return START_PHRASES[Math.floor(Math.random() * START_PHRASES.length)]
}
